services:
  postgres:
    container_name: flo_psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: flo
    image: postgres:13-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    restart: always

  node:
    container_name: flo-node
    build:
      context: .
      dockerfile: build/node_cached.Dockerfile
      args:
        BUILD_MODE: debug
    volumes:
      - ./.env:/usr/local/s2/.env
    depends_on:
      - postgres
    ports:
      - '127.0.0.1:3552:3552/udp'
      - '127.0.0.1:3553:3553'
      - '127.0.0.1:3554:3554/tcp'
      - '127.0.0.1:3555:3555'
    env_file:
      - .env

  controller:
    container_name: flo-controller
    build:
      context: .
      dockerfile: build/controller_cached.Dockerfile
      args:
        BUILD_MODE: debug
    volumes:
      - ./.env:/usr/local/s2/.env
    depends_on:
      postgres:
        condition: service_started
      node:
        condition: service_started
      db_initializer:
        condition: service_completed_successfully
    ports:
     - '127.0.0.1:3549:3549'
     - '127.0.0.1:3550:3550'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/flo
      # You need to run an instance of jaeger within your docker compose network
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
      # You need to run an instance of otel-collector within your docker compose network
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: flo-controller-local-compose
      OTEL_DEPLOYMENT_ENVIRONMENT: local-compose

  db_initializer:
    container_name: flo-db-initializer
    build:
      context: .
      dockerfile: local-init/db-initializer.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flo
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      NODE_EXTERNAL_IP: 127.0.0.1
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/flo
    volumes:
      - ./migrations:/usr/local/flo/migrations
      - ./diesel.toml:/usr/local/flo/diesel.toml
    depends_on:
      - postgres

volumes:
  database:

networks:
  default:
    name: w3c-network-local
    external: true
