[package]
name = "flo-otel"
version = "0.1.0"
authors = ["Jonas Krüger Svensson <jonas-ks@hotmail.com>"]
edition = "2021"

[dependencies]
tracing = { version = "0.1", default-features = false, features = ["log"]}
tracing-core = {version = "0.1"}
tracing-opentelemetry = { version = "0.30"  }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json"] }
opentelemetry = { version = "0.29", features = ["trace"] }
opentelemetry_sdk = { version = "0.29" }
opentelemetry-semantic-conventions = { version = "0.29.0", features = ["semconv_experimental"]}
# TODO: Use tonic instead of reqwest
opentelemetry-otlp = { version = "0.29.0", default-features = false, features = ["trace", "http-proto", "reqwest-blocking-client", "reqwest-rustls"]}
